name: PHPUnit Tests

on:
  push:
    branches: [ master ]
    paths-ignore:
    - 'README.md'
    - 'CHANGELOG.md'
    - 'VERSION'
    - 'docs/'

  pull_request:
    branches: [ master ]
    paths-ignore:
    - 'README.md'
    - 'CHANGELOG.md'
    - 'VERSION'
    - 'docs/'

jobs:
  build:

    runs-on: ubuntu-latest
    name: PHPUnit Tests
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: intl, json
        coverage: xdebug

    - name: Validate composer.json
      run: composer validate

    - name: Get Composer Cache Directory
      id: composer-cache
      run: |
        echo "::set-output name=dir::$(composer config cache-files-dir)"

    - name: Cache Composer Downloads
      uses: actions/cache@v1
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Install SQLite3
      run: composer require --no-update silverstripe/sqlite3

    - name: Install dependencies
      run: composer install --prefer-dist --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

    - name: Run PHPUnit Test Coverage
      run: vendor/bin/phpunit --coverage-clover=coverage.xml
      env:
        SS_DATABASE_CLASS: SQLite3Database
        SS_SQLITE_DATABASE_PATH: /tmp/database-file

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        flags: unittests
        fail_ci_if_error: false
