name: PHPUnit Tests

on:
  push:
    branches: [ master ]
    paths-ignore:
    - 'README.md'
    - 'VERSION'
    - 'docs/'

  pull_request:
    branches: [ master ]
    - 'README.md'
    - 'VERSION'
    - 'docs/'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json
      run: composer validate

    - name: Get Composer Cache Directory
      id: composer-cache
      run: |
        echo "::set-output name=dir::$(composer config cache-files-dir)"

    - name: Cache Composer Downloads
      uses: actions/cache@v1
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Install SQLite3
      run: composer require --no-update silverstripe/sqlite3

    - name: Install dependencies
      run: composer install --prefer-dist --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

    - name: Execute tests
      run: vendor/bin/phpunit
      env:
        SS_DATABASE_CLASS: SQLite3Database
        SS_SQLITE_DATABASE_PATH: /tmp/database-file