name: PHPUnit Tests

on:
  push:
    branches: [ master ]
    paths-ignore:
    - 'README.md'

  pull_request:
    branches: [ master ]

jobs:
  build-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install SQLite3
      run: composer require --no-update silverstripe/sqlite3

    - name: Install dependencies
      run: composer install --prefer-dist --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

    - name: Execute tests
      run: vendor/bin/phpunit
      env:
        SS_DATABASE_CLASS: SQLite3Database
        SS_SQLITE_DATABASE_PATH: /tmp/database-file