name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:5.7
        env:
            MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
            - 3306

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Execute tests
      run: vendor/bin/phpunit
      env:
        SS_DATABASE_USERNAME: root
        SS_DATABASE_PASSWORD: ''
        SS_DATABASE_PORT: ${{ job.services.mysql.ports[3306] }}